development:
  adapter: mysql2
  encoding: utf8
  database: foodudes
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: foodudes_test
  host: localhost
  username: root
  password:

production:

