development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
test:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
