development:
  adapter: mysql2
  encoding: utf8
  database: foodudes_development
  host: localhost
  username: root
  password:
  port: 13306
  socket: /opt/boxen/data/socket
test:
  adapter: mysql2
  encoding: utf8
  database: foodudes_test
  host: localhost
  username: root
  password:
  port: 13306
  socket: /opt/boxen/data/socket
production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
