development:
  adapter: mysql2
  encoding: utf8
  database: foodudes
  host: localhost
  username: root
  password:
  port: 13306
  socket: /opt/boxen/data/socket
test:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
